### PR TITLE
Deleted stupid discord api thingy

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by Froxcey — COMMENTED** [review]
No more 🍞👍? That's sad...

vibe

**Comment by ghost** [comment]
it's not, now it's just cringy and boring

**Comment by MrSerge01** [comment]
you didn't remove forgor @akane6704

**Comment by ghost** [comment]
ok now merg

**Review by MrSerge01 — APPROVED** [review]
LGTM,
-The Goos.

**Comment by MrSerge01** [comment]
@Froxcey review :trollface:

**Comment by Golem642** [comment]
Noooooo, not the bread !
image

**Pull request merged**
