### PR TITLE
Added a stupid easter egg

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by Froxcey — COMMENTED** [review]
Idk why I want to approve, but I don't manage this repo.

vibe

**Comment by MrSerge01** [comment]
ima review @froxcey

**Review by MrSerge01 — APPROVED** [review]
LGTM

**Comment by Froxcey** [comment]
> LGTM

LMAO it got merged

**Comment by ghost** [comment]
Wait WHAT

**Comment by MrSerge01** [comment]
lol

**Comment by TechStudent10** [comment]
Bruh and #23 didn't get merged.

**Pull request merged**
