### PR TITLE
Updated Help Command

### PR DESCRIPTION
**Pull request by Rohith0009**
Renamed 'Test' to 'Commands'. When Using Slash Command `help` updated all the command options

### CODE REVIEW

**Review by MrSerge01 — CHANGES_REQUESTED** [review]
kinda nice but a small nitpick; why "RepoList"? its just called "repolist".

also a funny question: why you're doing PRs when you have exams and are on LOA? :trollface:

**Comment by Rohith0009** [comment]
> also a funny question: why you're doing PRs when you have exams and are on LOA? :trollface:
Yah, I Am Having A Bit Of Free Time.

**Comment by Rohith0009** [comment]
> kinda nice but a small nitpick; why "RepoList"? its just called "repolist".
Changed it.

**Review by MrSerge01 — APPROVED** [review]
LGTM

**Comment by MrSerge01** [comment]
> > also a funny question: why you're doing PRs when you have exams and are on LOA? :trollface:
> > Yah, I Am Having A Bit Of Free Time.

ight

**Pull request merged**
