### PR TITLE
Revert "Add config.json file and loa slash command"

### PR DESCRIPTION
**Pull request by Golem642**
We are going to keep the loa command and the config file but you messed up a lot with the visual syntax which we didn't appreciate, sorry.

### CODE REVIEW

**Comment by MrSerge01** [comment]
you deleted the loa command and config.json

**Comment by Golem642** [comment]
I will add them back afterwards and credit the person who made it

**Comment by MrSerge01** [comment]
alright, merge

**Comment by MCUxDaredevil** [comment]
> We are going to keep the loa command and the config file but you messed up a lot with the visual syntax which we didn't appreciate, sorry.

@Golem642 You mean the tabs and stuff?
If so maybe we can have a configuration file such as a .prettierc file if most people use vscode with prettier
That way the syntax will stay the same for anyone collaborating on this

**Comment by Golem642** [comment]
> > We are going to keep the loa command and the config file but you messed up a lot with the visual syntax which we didn't appreciate, sorry.
> 
> @Golem642 You mean the tabs and stuff? If so maybe we can have a configuration file such as a .prettierc file if most people use vscode with prettier That way the syntax will stay the same for anyone collaborating on this

@MCUxDaredevil Maybe, i personnally don't use prettier for now but if you want to to this file you can, just make sure to follow what the current code format looks like.

**Comment by MCUxDaredevil** [comment]
> > > We are going to keep the loa command and the config file but you messed up a lot with the visual syntax which we didn't appreciate, sorry.
> > 
> > @Golem642 You mean the tabs and stuff? If so maybe we can have a configuration file such as a .prettierc file if most people use vscode with prettier That way the syntax will stay the same for anyone collaborating on this
> 
> @MCUxDaredevil Maybe, i personnally don't use prettier for now but if you want to to this file you can, just make sure to follow what the current code format looks like.

 Let me know what settings or formatter you use and I'll set it up the same way

**Comment by Golem642** [comment]
@MCUxDaredevil i don't use a formatter, extensions i have on vscode are only languages extensions, and github and share stuff

**Comment by MCUxDaredevil** [comment]
> @MCUxDaredevil i don't use a formatter, extensions i have on vscode are only languages extensions, and github and share stuff

Ohh ok then just let me know what your settings in vscode are. Like the tab size and stuff

**Comment by Golem642** [comment]
> > @MCUxDaredevil i don't use a formatter, extensions i have on vscode are only languages extensions, and github and share stuff
> 
> Ohh ok then just let me know what your settings in vscode are. Like the tab size and stuff

They are all default except tab size which is 2

**Comment by MCUxDaredevil** [comment]
👍

**Pull request merged**
