### PR TITLE
Add config.json file and loa slash command

### PR DESCRIPTION
**Pull request by MCUxDaredevil**
- Added a config file to access values dynamically instead of using constant strings
- Added loa slash command that sets (not applies) loa for a developer and removes when they return

### CODE REVIEW

**Comment by MrSerge01** [comment]
Why make a config.json when we already have .env? I can add the things you added to .env and update the guide.
@MCUxDaredevil

**Comment by MCUxDaredevil** [comment]
The env can be kept for things that we don't want others to see and things that are kinda permanent or sensitive
Like the token. While the config will contain stuff that can be public like the servers ids and stuff, and things that are not quite permanent.
Also I dont think adding prefix to env vars is a good idea since we are changing it with commands
I'm not sure how directly doing `process.env.PREFIX = newPrefix` works but afaik the prefix will reset from the .env file every time we restart the bot

**Comment by MCUxDaredevil** [comment]
@MrSerge01 We can also use mongo to keep the config data so we don't have to modify any of the files directly
We can just change the values in the db

**Comment by MrSerge01** [comment]
Welp, I'm going to merge.

**Pull request merged**
