### PR TITLE
Make it so that when ever you say "honk" it reacts with goos standing

### PR DESCRIPTION
**Pull request by TechStudent10**
Example:

image

Not sure if it works though

### CODE REVIEW

**Review by MrSerge01 — CHANGES_REQUESTED** [review]
It won't work. ~~LGTM~~

I have an answer tho.
```js
const goosStanding = client.emojis.cache.get("993799647015481397");
// afterwards..
[['honk'], () => message.react(goosStanding)];
```

**Review by MrSerge01 — CHANGES_REQUESTED** [review]
You put it outside the `module.exports`..
..but this needs the `client` which is only in `module.exports` :trollface: 
Please put it inside the `module.exports` so it will actually work.
@TechStudent11

**Comment by TechStudent10** [comment]
Oops sorry. Haven't used JS in a while (been primarily sharpening my Python skills)

**Review by MrSerge01 — APPROVED** [review]
After ages, after centuries...






LGTM

**Comment by AZProductions** [comment]
Goos pro, pigpot noob

**Pull request merged**
