### PR TITLE
Added More Commands

### PR DESCRIPTION
**Pull request by Rohith0009**
Added More Commands and improved some commands

### CODE REVIEW

**Review by StoneMcYT — CHANGES_REQUESTED** [review]
Mhm as the bot is being rewritten to type script at the moment i  do not think this features are required +  when  WM

**Comment by Rohith0009** [comment]
> when WM

btw what is 'WM'

**Comment by Rohith0009** [comment]
Should I Close The PR?

**Comment by MrSerge01** [comment]
*appears*
what

**Comment by Rohith0009** [comment]
> _appears_ what

??

**Review by Froxcey — CHANGES_REQUESTED** [review]
The bot is currently getting a typescript rewrite, so please commit to that branch instead. 

> wm

Window manager. We should still allow contributions outside of the wm repo since it would be weird to require every dev to work on rust code. It's just the upper team will be more focused on wm and will review less often.

**Comment by MrSerge01** [comment]
> The bot is currently getting a typescript rewrite, so please commit to that branch instead.
> 
> > wm
> 
> Window manager. We should still allow contributions outside of the wm repo since it would be weird to require every dev to work on rust code. It's just the upper team will be more focused on wm and will review less often.

also, there's the grand pull request that uh makes Tinan TS-ified and made other stuff

**Comment by ghost** [comment]
Closing

**Pull request closed without merging**
