### PR TITLE
TS-IFY! (this is a new branch, cbf to update the ts-rewrite branch)

### PR DESCRIPTION
**Pull request by Paraxdev**
What I did:
- Remove old code base
- Import a code base for a typescript bot I've created (repo can be found on my profile)
- Add Event and Slash Command Handler
- Port some commands from the old bot

BUGS / TODO:
- LOA Needs to be checked
- apparently bot cannot build? (it builds, but commands do not load commands in prod.)
- Add modals and contextmenus?

USAGE:
- This is strict typescript, meaning that interactions sometimes yield multiple types (Original type we want, and an "API" version, this version is pretty much useless, so we need to cast most things. (like: (interaction.user as User).id;
- Commands and events basically are classes where it just uses constructors for everything we need (builder data, permissions and run function)

### CODE REVIEW

**Comment by Paraxdev** [comment]
It's still WIP and needs a lot of testing, the next thing I will add is a README for documentation on how to run it

**Comment by MrSerge01** [comment]
maybe make it a draft PR if it's in progress? @Xapu1337 
also I am doing an entirely new README.md and contribution guidelines, so maybe don't touch that.
upon further review, WHY. this really deserves to be in a ts-rewrite branch because not only did you rewrite the bot to TS, you changed the convention of naming, the entire bot structure, like why?

**Comment by MrSerge01** [comment]
and of course, in those contribution guidelines, I have made this for developers like you.
Screenshot_24

**Comment by Paraxdev** [comment]
> maybe make it a draft PR if it's in progress? @Xapu1337 
> also I am doing an entirely new README.md and contribution guidelines, so maybe don't touch that.
> upon further review, WHY. this really deserves to be in a ts-rewrite branch because not only did you rewrite the bot to TS, you changed the convention of naming, the entire bot structure, like why?
> 

Pretty much because the old one would make an sense as that one ignores types and the structure is semi important. for typescript you may want to split up to folders and classes as this gives both a uniformly structured code but also types (classes can be used as types)

**Comment by Paraxdev** [comment]
Also on why a TS rewrite, types can make coding easier as you get compile errors before you run the bot only to find out that something doesn't exist but you also get better IDE completions.

and yeah I'll close this one and reopen it as a draft

**Pull request closed without merging**
